version: '3.8'

services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../deployment/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
      - SECRET_KEY=engday2026_super_secret_key_docker
      - JWT_SECRET=engday2026_jwt_secret_key_docker
      - JUDGE0_URL=https://judge0-ce.p.rapidapi.com
    restart: always

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../deployment/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: always
